workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

variables:
  UV_VERSION: "0.12.15"
  PYTHON_VERSION: "3.12"
  BASE_LAYER: trixie-slim
  UV_LINK_MODE: copy
  UV_CACHE_DIR: .uv-cache

stages:
  - lint

default:
  image: ghcr.io/astral-sh/uv:$UV_VERSION-python$PYTHON_VERSION-$BASE_LAYER
  cache:
    - key:
        files:
          - uv.lock
      paths:
        - $UV_CACHE_DIR
  before_script:
    - uv sync --locked
  after_script:
    - uv cache prune --ci

lint-python:
  stage: lint
  script:
    - uv run ruff check .
    - uv run ruff format --check .

lint-dbt:
  stage: lint
  script:
    - uv run sqlfluff lint src/dbt

lint-yaml:
  stage: lint
  script:
    - uv run yamllint .
